Update README.md
After activating venv I'm in a subfolder... so instruction need to go up a level to access ..\requirements.txt

Without this I get the error:
pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'